In [ ]:
print("hello world")

hello world


In [1]:
import tensorflow as tf

In [2]:
mat = tf.Variable([[25., 2.], [3, 4]])

In [3]:
tf.print(mat)

[[25 2]
 [3 4]]


In [4]:
tf.linalg.det(mat)

<tf.Tensor: shape=(), dtype=float32, numpy=94.00001525878906>

In [8]:
mat1 = tf.Variable([[-2., 0.], [0., -2.]])

In [10]:
tf.print(mat1)
tf.linalg.det(mat1)

[[-2 0]
 [0 -2]]


<tf.Tensor: shape=(), dtype=float32, numpy=4.0>

In [13]:
mat2 = tf.Variable([[2., 1., -3.], [4., -5., 2.], [0., -1., 3.]])
tf.print(mat2)
tf.linalg.det(mat2)

[[2 1 -3]
 [4 -5 2]
 [0 -1 3]]


<tf.Tensor: shape=(), dtype=float32, numpy=-25.99999237060547>